name: Builders-Utilities
version: "${version}"
api-version: 1.13
main: net.arcaniax.buildersutilities.BuildersUtilities
authors: [ Ktar5, Arcaniax ]
website: "https://www.spigotmc.org/resources/42361/"
commands:
  butil:
    aliases: bu
    description: opens toggle menu
    permission: builders.util.gui
  banner:
    description: opens banner creator
    aliases: bm
    permission: builders.util.banner
  armorcolor:
    description: opens armor color creator
    aliases: color
    permission: builders.util.color
  nc:
    aliases: noclip
    description: Toggles NoClip.
    permission: builders.util.noclip
  af:
    aliases: advfly
    description: Toggles Advanced fly.
    permission: builders.util.advancedfly
  n:
    aliases: nv
    description: Toggles Nightvision.
    permission: builders.util.nightvision
  /r:
    description: alias
    permission: builders.util.aliases
  /s:
    description: alias
    permission: builders.util.aliases
  /c:
    description: alias
    permission: builders.util.aliases
  /f:
    description: alias
    permission: builders.util.aliases
  /pa:
    description: alias
    permission: builders.util.aliases
  /derot:
    description: alias
    permission: builders.util.aliases
  /twist:
    description: alias
    permission: builders.util.aliases
  /scale:
    description: alias
    permission: builders.util.aliases
  /cuboid:
    description: alias
    aliases: /cub
    permission: builders.util.aliases
  /flip:
    description: alias
    permission: builders.util.aliases
  /convex:
    description: alias
    aliases: /con
    permission: builders.util.aliases
  blocks:
    description: Opens secret blocks menu
    aliases: secretblocks
    permission: builders.util.secretblocks
  ws:
    description: alias
    permission: builders.util.aliases
  fs:
    description: alias
    permission: builders.util.aliases

permissions:
  builders.util.trapdoor:
    default: true
  builders.util.slabs:
    default: true
  builders.util.terracotta:
    default: true
  builders.util.nightvision:
    default: op
  builders.util.noclip:
    default: op
  builders.util.advancedfly:
    default: op
